
clean:
	rm 6838_project.aux ||:
	rm 6838_project.brf ||:
	rm 6838_project.fdb_latexmk ||:
	rm 6838_project.fls ||:
	rm 6838_project.lbl ||:
	rm 6838_project.log ||:
	rm 6838_project.pdf ||:
	rm 6838_project.synctex.gz ||: